// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseProtocolMsg.proto

package com.common.protocol;

public final class MsgProtobuf {
  private MsgProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ProtocolMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
     * @return The type.
     */
    com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType getType();

    /**
     * <code>string fromUserId = 2;</code>
     * @return The fromUserId.
     */
    java.lang.String getFromUserId();
    /**
     * <code>string fromUserId = 2;</code>
     * @return The bytes for fromUserId.
     */
    com.google.protobuf.ByteString
        getFromUserIdBytes();

    /**
     * <code>string toUserId = 3;</code>
     * @return The toUserId.
     */
    java.lang.String getToUserId();
    /**
     * <code>string toUserId = 3;</code>
     * @return The bytes for toUserId.
     */
    com.google.protobuf.ByteString
        getToUserIdBytes();

    /**
     * <code>string msg = 4;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 4;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code protocol.ProtocolMsg}
   */
  public static final class ProtocolMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ProtocolMsg)
      ProtocolMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtocolMsg.newBuilder() to construct.
    private ProtocolMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolMsg() {
      type_ = 0;
      fromUserId_ = "";
      toUserId_ = "";
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtocolMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtocolMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fromUserId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              toUserId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.common.protocol.MsgProtobuf.internal_static_protocol_ProtocolMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.common.protocol.MsgProtobuf.internal_static_protocol_ProtocolMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.common.protocol.MsgProtobuf.ProtocolMsg.class, com.common.protocol.MsgProtobuf.ProtocolMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code protocol.ProtocolMsg.MsgEnumType}
     */
    public enum MsgEnumType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MSG_TYPE_GROUP = 0;</code>
       */
      MSG_TYPE_GROUP(0),
      /**
       * <code>MSG_TYPE_PRIVATE = 1;</code>
       */
      MSG_TYPE_PRIVATE(1),
      /**
       * <code>MSG_TYPE_HEARTBEAT = 2;</code>
       */
      MSG_TYPE_HEARTBEAT(2),
      /**
       * <code>MSG_TYPE_LOGIN = 3;</code>
       */
      MSG_TYPE_LOGIN(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>MSG_TYPE_GROUP = 0;</code>
       */
      public static final int MSG_TYPE_GROUP_VALUE = 0;
      /**
       * <code>MSG_TYPE_PRIVATE = 1;</code>
       */
      public static final int MSG_TYPE_PRIVATE_VALUE = 1;
      /**
       * <code>MSG_TYPE_HEARTBEAT = 2;</code>
       */
      public static final int MSG_TYPE_HEARTBEAT_VALUE = 2;
      /**
       * <code>MSG_TYPE_LOGIN = 3;</code>
       */
      public static final int MSG_TYPE_LOGIN_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgEnumType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgEnumType forNumber(int value) {
        switch (value) {
          case 0: return MSG_TYPE_GROUP;
          case 1: return MSG_TYPE_PRIVATE;
          case 2: return MSG_TYPE_HEARTBEAT;
          case 3: return MSG_TYPE_LOGIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgEnumType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgEnumType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgEnumType>() {
              public MsgEnumType findValueByNumber(int number) {
                return MsgEnumType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.common.protocol.MsgProtobuf.ProtocolMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgEnumType[] VALUES = values();

      public static MsgEnumType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgEnumType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.ProtocolMsg.MsgEnumType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType getType() {
      @SuppressWarnings("deprecation")
      com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType result = com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType.valueOf(type_);
      return result == null ? com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType.UNRECOGNIZED : result;
    }

    public static final int FROMUSERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object fromUserId_;
    /**
     * <code>string fromUserId = 2;</code>
     * @return The fromUserId.
     */
    @java.lang.Override
    public java.lang.String getFromUserId() {
      java.lang.Object ref = fromUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUserId_ = s;
        return s;
      }
    }
    /**
     * <code>string fromUserId = 2;</code>
     * @return The bytes for fromUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromUserIdBytes() {
      java.lang.Object ref = fromUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOUSERID_FIELD_NUMBER = 3;
    private volatile java.lang.Object toUserId_;
    /**
     * <code>string toUserId = 3;</code>
     * @return The toUserId.
     */
    @java.lang.Override
    public java.lang.String getToUserId() {
      java.lang.Object ref = toUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUserId_ = s;
        return s;
      }
    }
    /**
     * <code>string toUserId = 3;</code>
     * @return The bytes for toUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToUserIdBytes() {
      java.lang.Object ref = toUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 4;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 4;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType.MSG_TYPE_GROUP.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getFromUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fromUserId_);
      }
      if (!getToUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, toUserId_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType.MSG_TYPE_GROUP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getFromUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fromUserId_);
      }
      if (!getToUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, toUserId_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.common.protocol.MsgProtobuf.ProtocolMsg)) {
        return super.equals(obj);
      }
      com.common.protocol.MsgProtobuf.ProtocolMsg other = (com.common.protocol.MsgProtobuf.ProtocolMsg) obj;

      if (type_ != other.type_) return false;
      if (!getFromUserId()
          .equals(other.getFromUserId())) return false;
      if (!getToUserId()
          .equals(other.getToUserId())) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUserId().hashCode();
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.common.protocol.MsgProtobuf.ProtocolMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.common.protocol.MsgProtobuf.ProtocolMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ProtocolMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ProtocolMsg)
        com.common.protocol.MsgProtobuf.ProtocolMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.common.protocol.MsgProtobuf.internal_static_protocol_ProtocolMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.common.protocol.MsgProtobuf.internal_static_protocol_ProtocolMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.common.protocol.MsgProtobuf.ProtocolMsg.class, com.common.protocol.MsgProtobuf.ProtocolMsg.Builder.class);
      }

      // Construct using com.common.protocol.MsgProtobuf.ProtocolMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        fromUserId_ = "";

        toUserId_ = "";

        msg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.common.protocol.MsgProtobuf.internal_static_protocol_ProtocolMsg_descriptor;
      }

      @java.lang.Override
      public com.common.protocol.MsgProtobuf.ProtocolMsg getDefaultInstanceForType() {
        return com.common.protocol.MsgProtobuf.ProtocolMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.common.protocol.MsgProtobuf.ProtocolMsg build() {
        com.common.protocol.MsgProtobuf.ProtocolMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.common.protocol.MsgProtobuf.ProtocolMsg buildPartial() {
        com.common.protocol.MsgProtobuf.ProtocolMsg result = new com.common.protocol.MsgProtobuf.ProtocolMsg(this);
        result.type_ = type_;
        result.fromUserId_ = fromUserId_;
        result.toUserId_ = toUserId_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.common.protocol.MsgProtobuf.ProtocolMsg) {
          return mergeFrom((com.common.protocol.MsgProtobuf.ProtocolMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.common.protocol.MsgProtobuf.ProtocolMsg other) {
        if (other == com.common.protocol.MsgProtobuf.ProtocolMsg.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getFromUserId().isEmpty()) {
          fromUserId_ = other.fromUserId_;
          onChanged();
        }
        if (!other.getToUserId().isEmpty()) {
          toUserId_ = other.toUserId_;
          onChanged();
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.common.protocol.MsgProtobuf.ProtocolMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.common.protocol.MsgProtobuf.ProtocolMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType getType() {
        @SuppressWarnings("deprecation")
        com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType result = com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType.valueOf(type_);
        return result == null ? com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.common.protocol.MsgProtobuf.ProtocolMsg.MsgEnumType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ProtocolMsg.MsgEnumType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fromUserId_ = "";
      /**
       * <code>string fromUserId = 2;</code>
       * @return The fromUserId.
       */
      public java.lang.String getFromUserId() {
        java.lang.Object ref = fromUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fromUserId = 2;</code>
       * @return The bytes for fromUserId.
       */
      public com.google.protobuf.ByteString
          getFromUserIdBytes() {
        java.lang.Object ref = fromUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fromUserId = 2;</code>
       * @param value The fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fromUserId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUserId() {
        
        fromUserId_ = getDefaultInstance().getFromUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string fromUserId = 2;</code>
       * @param value The bytes for fromUserId to set.
       * @return This builder for chaining.
       */
      public Builder setFromUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromUserId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toUserId_ = "";
      /**
       * <code>string toUserId = 3;</code>
       * @return The toUserId.
       */
      public java.lang.String getToUserId() {
        java.lang.Object ref = toUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string toUserId = 3;</code>
       * @return The bytes for toUserId.
       */
      public com.google.protobuf.ByteString
          getToUserIdBytes() {
        java.lang.Object ref = toUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toUserId = 3;</code>
       * @param value The toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string toUserId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUserId() {
        
        toUserId_ = getDefaultInstance().getToUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string toUserId = 3;</code>
       * @param value The bytes for toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toUserId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 4;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 4;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 4;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 4;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ProtocolMsg)
    }

    // @@protoc_insertion_point(class_scope:protocol.ProtocolMsg)
    private static final com.common.protocol.MsgProtobuf.ProtocolMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.common.protocol.MsgProtobuf.ProtocolMsg();
    }

    public static com.common.protocol.MsgProtobuf.ProtocolMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtocolMsg>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolMsg>() {
      @java.lang.Override
      public ProtocolMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtocolMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtocolMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.common.protocol.MsgProtobuf.ProtocolMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ProtocolMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ProtocolMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025BaseProtocolMsg.proto\022\010protocol\"\326\001\n\013Pr" +
      "otocolMsg\022/\n\004type\030\001 \001(\0162!.protocol.Proto" +
      "colMsg.MsgEnumType\022\022\n\nfromUserId\030\002 \001(\t\022\020" +
      "\n\010toUserId\030\003 \001(\t\022\013\n\003msg\030\004 \001(\t\"c\n\013MsgEnum" +
      "Type\022\022\n\016MSG_TYPE_GROUP\020\000\022\024\n\020MSG_TYPE_PRI" +
      "VATE\020\001\022\026\n\022MSG_TYPE_HEARTBEAT\020\002\022\022\n\016MSG_TY" +
      "PE_LOGIN\020\003B\"\n\023com.common.protocolB\013MsgPr" +
      "otobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_ProtocolMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_ProtocolMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ProtocolMsg_descriptor,
        new java.lang.String[] { "Type", "FromUserId", "ToUserId", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
